config/routes.rb
Rails.application.routes.draw do
scope ":locale",locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users
  resources :costs
  resources :incomes
  resources :categories
  root to: 'costs#index'
end
match '*path', to: redirect {|params| "/#{I18n.default_locale}/#{params[:path]}"}, constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }, via: :get
match '', :via => [:get], to: redirect("/#{I18n.default_locale}")

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :costs, dependent: :destroy
	has_many :incomes, dependent: :destroy
	validates :name, presence: true
end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :category
  validates :amount, presence: true
  validates :category_id, presence: true
end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :category
  validates :amount, presence: true
  validates :category_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale
 
  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
  def default_url_options(options={})
	{locale: I18n.locale}
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
    @user = current_user	
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)
    @cost.email = current_user.email
    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:category_id, :amount)
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = Income.new(income_params)
	@income.email = current_user.email
    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def income_params
      params.require(:income).permit(:category_id, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to I18n.t('views.show'), @category %> |
<%= link_to I18n.t('views.back'), categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= I18n.t('views.listcat') %></h1>

<table class="coststb">
  <thead>
    <tr>
      <th><%= Category.human_attribute_name(:name) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to I18n.t('views.show'), category %></td>
        <td><%= link_to I18n.t('views.edit'), edit_category_path(category) %></td>
        <td><%= link_to I18n.t('views.destroy'), category, method: :delete, data: { confirm: I18n.t('views.are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to I18n.t('views.cost.index.new_product3'), new_category_path %>
<%= link_to I18n.t('views.back'), costs_path %>

app/views/categories/new.html.erb
<h1><%= I18n.t('views.cost.index.new_product3') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), costs_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Category.human_attribute_name(:name) %>:</strong>
  <%= @category.name %>
</p>

<%= link_to I18n.t('views.edit'), edit_category_path(@category) %> |
<%= link_to I18n.t('views.back'), categories_path %>

app/views/costs/_form.html.erb
<%= form_for(@cost) do |f| %>
  <% if @cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% @cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field" style="display:inline-block;">
  <%= f.label :category_id %><br>
	<%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>    
    <span class="spanlink"><%= I18n.t('views.orclick')%> <%= link_to I18n.t('views.here'), new_category_path %> <%= I18n.t('views.create')%></span>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1><%= I18n.t('views.cost.edit.title') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.show'), @cost %> |
<%= link_to I18n.t('views.back'), costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>
<% if current_user %>
<h1 style = "font-family:'Brush Script MT', cursive;color:blue;font-size:5em;"><%= I18n.t('views.mainpagetitle') %></h1>
<% if (Cost.where(:created_at => Time.now.beginning_of_month..Time.now.end_of_month, :email => current_user.email).sum(:amount)) > 200 %>
<div class="alert"><%= image_tag("alert") %></div>
<div style="font-family:'Brush Script MT', cursive;color:red;font-size:35px;position:absolute;right:5px;margin-top:180px;"><%= I18n.t('views.spent') %></div>
<% end %>
<% if (Cost.where(:email => current_user.email).count(:amount) > 0) || (Income.where(:email => current_user.email).count(:amount) > 0)%>
<table class="coststb">
  <thead>
    <tr>	  	
      <th><%= Cost.human_attribute_name(:type) %></th>	
	  <th><%= Cost.human_attribute_name(:date) %></th>
      <th><%= Cost.human_attribute_name(:category) %></th>
      <th><%= Cost.human_attribute_name(:amount) %></th>	 			
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
	<%if current_user.email == cost.email%>
      <tr style="color:red;">
		<td><%= I18n.t('views.expense') %></td>
	  <td><%= cost.created_at.strftime("%m/%d/%Y") %></td>
        <td><% if cost.category %><%= cost.category.name %><%end%></td>
        <td><%= number_to_currency(cost.amount) %></td>				
        <td><%= link_to I18n.t('views.show'), cost %></td>
        <td><%= link_to I18n.t('views.edit'), edit_cost_path(cost) %></td>
        <td><%= link_to I18n.t('views.destroy'), cost, method: :delete, data: { confirm: I18n.t('views.are_you_sure') } %></td>
      </tr>
	  <%end%>
    <% end %>
	<% Income.all.each do |income| %>
	<%if current_user.email == income.email%>
      <tr style="color:green;">	  
	  <td><%= I18n.t('views.income') %></td>
	  <td><%= Time.now.strftime("%m/%d/%Y") %></td>
        <td><% if income.category %><%= income.category.name %><%end%></td>
        <td><%= number_to_currency(income.amount) %></td>				
        <td><%= link_to I18n.t('views.show'), income %></td>
        <td><%= link_to I18n.t('views.edit'), edit_income_path(income) %></td>
        <td><%= link_to I18n.t('views.destroy'), income, method: :delete, data: { confirm: I18n.t('views.are_you_sure') } %></td>
      </tr>
	  <%end%>
    <% end %>
  </tbody>
</table>
<%end%>
<h2 style = "font-family:'Brush Script MT', cursive;color:blue;font-size:3em;"><%= I18n.t('views.availablebalance') %>:<label style="color:crimson;"> $<%=Income.where(:email => current_user.email).sum(:amount) - Cost.where(:email => current_user.email).sum(:amount) %></label></h2>
<h2 style = "font-family:'Brush Script MT', cursive;color:blue;font-size:3em;display:inline-block;"><%= I18n.t('views.bills') %>:</h2>
<%= link_to image_tag("bofa.jpg", :size => "70x50"), "https://www.bankofamerica.com/" %>
<%= link_to image_tag("chase.jpg", :size => "70x50"), "https://www.chase.com/" %>
<%= link_to image_tag("wellsfargo.jpg", :size => "70x50"), "https://www.wellsfargo.com/" %>
<br>
<%else%>
<h1 style="text-align:center;margin-top:300px;color:red;">Sign in above to enjoy the benefits of Wallet App!!! </h1>
<%end%>

app/views/costs/new.html.erb
<h1><%=I18n.t('views.cost.index.new_product2') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Cost.human_attribute_name(:category) %>:</strong>
  <% if @cost.category %><%= @cost.category.name %> <% end %>
</p>

<p>
  <strong><%= Cost.human_attribute_name(:amount)%>:</strong>
  <%= number_to_currency(@cost.amount) %>
</p>

<%= link_to link_to I18n.t('views.edit'), edit_cost_path(@cost) %> |
<%= link_to link_to I18n.t('views.back'), costs_path %>

app/views/incomes/_form.html.erb
<%= form_for(@income) do |f| %>
  <% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
      <% @income.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field" style="display:inline-block;">
  <%= f.label :category_id %><br>
	<%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </div>    
  <span class="spanlink"><%= I18n.t('views.orclick') %> <%= link_to I18n.t('views.here'), new_category_path %> <%= I18n.t('views.create') %></span>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form' %>

<%= link_to I18n.t('views.show'), @income %> |
<%= link_to I18n.t('views.back'), costs_path %>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= I18n.t('views.cost.index.new_product') %></h1>

<table class="coststb">
  <thead>
    <tr>
      <th><%= Income.human_attribute_name(:category) %></th>
      <th><%= Income.human_attribute_name(:amount) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incomes.each do |income| %>
      <tr>
        <td><% if income.category %><%= income.category.name %><%end%></td>
        <td><%= income.amount %></td>
        <td><%= link_to I18n.t('views.show'), income %></td>
        <td><%= link_to I18n.t('views.edit'), edit_income_path(income) %></td>
        <td><%= link_to I18n.t('views.destroy'), income, method: :delete, data: { confirm: I18n.t('views.are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to I18n.t('views.back'), costs_path %>

app/views/incomes/new.html.erb
<h1><%=I18n.t('views.cost.index.new_product') %></h1>

<%= render 'form' %>

<%= link_to I18n.t('views.back'), costs_path %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Income.human_attribute_name(:category) %>:</strong>
  <% if @income.category %><%= @income.category.name %> <% end %>
</p>

<p>
  <strong><%= Income.human_attribute_name(:amount) %>:</strong>
  <%= number_to_currency(@income.amount) %>
</p>

<%= link_to I18n.t('views.edit'), edit_income_path(@income) %> |
<%= link_to I18n.t('views.back'), costs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>	  
  <%= csrf_meta_tags %>
</head>
<body class="body">
<div class="collapse">
				<ul class="nav">
					<li class="hidden">
						<a href="#page-top"></a>
					</li>
					<% if current_user %>
					<li>
						<%= link_to(I18n.t('views.home'), root_path) %>
					</li>
					<li>						
					<label style="font-size:25px;text-decoration:underline;"><%= I18n.t('views.language') %></label>:
					<%= link_to_unless I18n.locale == :en, "English", locale: :en %>
					|
					<%= link_to_unless I18n.locale == :ru, "Russian", locale: :ru %>
					</li>
					<li>
						<%= link_to I18n.t('views.cost.index.new_product'), new_income_path %>
					</li>
					<li>
						<%= link_to I18n.t('views.cost.index.new_product2'), new_cost_path %>						
					</li> 
					<li>
						<%= link_to I18n.t('views.cost.index.managecategory'), categories_path %>
					</li>
<%end %>					
					<li>
						<% if current_user %>		
		<div style="float:right;"><%= link_to "Logout", destroy_user_session_path, :method => :delete %></div>
	<% else %>
		<%= link_to "Sign in",new_user_session_path %><br />
		<label style="float:right;font-size:20px;margin-top:15px;">Not Registered? Click  <%= link_to "here", new_user_registration_path %> to sign up</label>
	<% end %>
					</li>
				</ul>
			</div>
<% if current_user %>               			
	<h1 style = "font-family:'Brush Script MT', cursive;color:darkturquoise;font-size:5em;display:inline-block;margin-top:72px;"><%= I18n.t('views.hello') %> <%= current_user.email[/[^@]+/] %></h1>
<label style="float:right;margin-top:50px;"> Logged in as <%= current_user.email %> </label>	
<% end %>						
<div style="color:white;text-align:right;font-size:1.8em;display:inline-block;margin-top:35px;" ></div>	
<%= yield %>

</body>
</html>